// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// BlogController is an autogenerated mock type for the BlogController type
type BlogController struct {
	mock.Mock
}

// CreateNewBlog provides a mock function with given fields: c
func (_m *BlogController) CreateNewBlog(c *gin.Context) {
	_m.Called(c)
}

// GetAllBlogs provides a mock function with given fields: c
func (_m *BlogController) GetAllBlogs(c *gin.Context) {
	_m.Called(c)
}

// NewBlogController creates a new instance of BlogController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlogController(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlogController {
	mock := &BlogController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
