// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	models "go-clean-arch/models"

	mock "github.com/stretchr/testify/mock"
)

// UserUsecase is an autogenerated mock type for the UserUsecase type
type UserUsecase struct {
	mock.Mock
}

// RegisterUser provides a mock function with given fields: data
func (_m *UserUsecase) RegisterUser(data *models.CreateUserDto) (int, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.CreateUserDto) (int, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func(*models.CreateUserDto) int); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(*models.CreateUserDto) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserUsecase creates a new instance of UserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUsecase {
	mock := &UserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
